version: "3"

services:
  smppsim:
    image: eagafonov/smppsim
    container_name: smppsim
    ports:
      - 3785:2775
  redis:
    image: redis:alpine
    restart: unless-stopped

  rabbit-mq:
    image: rabbitmq:alpine
    restart: unless-stopped

  jasmin:
    image: jookies/jasmin:0.10
    restart: unless-stopped
    container_name: jasmin
    volumes:
      - /var/log/jasmin:/var/log/jasmin
      #- /etc/jasmin:/etc/jasmin
      - /etc/jasmin/store:/etc/jasmin/store

    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
    depends_on:
      - redis
      - rabbit-mq
    environment:
      REDIS_CLIENT_HOST: redis
      AMQP_BROKER_HOST: rabbit-mq
      SMPPSIM: smppsim
